before_script:
  - echo ‘deb-src ftp://ftp.us.debian.org/debian/ sid main contrib non-free’ >> /etc/apt/sources.list
  - apt update -qy
  - apt-get build-dep bitcoin
  - apt-get –install-recommends install libbitcoin-dev

stages:
  - build

basic-build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure –with-incompatible-bdb
    - make

  only:
    - master
  tags:
    - debian
    - jessie
