before_script:
  - echo 'deb-src ftp://ftp.us.debian.org/debian/ sid main contrib non-free' >> /etc/apt/sources.list
  - apt update -qy
  - apt-get -y build-dep bitcoin
  - apt-get -y --install-recommends install libbitcoin-dev

stages:
  - build

basic-build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure --with-incompatible-bdb --without-gui --disable-wallet --without-miniupnpc
    - dpkg-buildpackage -b

  only:
    - master
  tags:
    - debian
    - jessie
